appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LDB0xX1tL2Ohrk7PybSKQDPNFl30x0uenbVwLY3B5UCiIEd9hRZ2wKWoEmR9LVzI8PvaEtb4a3cebS2gWjpD4+L6yaag+zu+dv5o/q13eiOrdtLD6eTzbRHWr4dpPddJAeZPUC/2woZxYM6HuqKAJhz1lQ8HulbJqmktKTtEOgxUzgs1NJzedHTg/D+gs2gg9EYiYdLY+7NikKhaMWsUzcJDD4z/ohwzCoqECDVuIlgtpGEwMDGtYJsFSXLp6e9pr21qJZ9+MTVDgE6zxiSiosFkmqDHXmPXi6kzRFyyj4tuVhSfgxjdKRqdr3oD5cCpxEtHGaYYgIoctrsvSvFrlBF9hOB76pD9Sr2ygKW5uyyLZ1sXzdXBYmy0RSIHw76MVyU/UIil6QD19bGC0vge7miBan/3eGvGlGMzOkZ6B4GKx8xfBElwL7IvvkO4ju1StwbqawfL6KPuUeDTFGZ4yfDcGwUXvMeku31+jkGiFNBigQ9MsvtXBxSqxKmYmUzcEfidB0qvEELVnHeSzKuYp5wwH1H/AfAOeW9AplG/+ERukEb8UxchIOSFd1G9U/jyIf17S+YQFjDCCJ0m37Xg68qQ+D6iVfK4AELsJvcELt0tUXqXjokHLUqbI9rzEGE0cTvmMDE3+BZnQhWOLh0xazWW7NdQp6610wo9fCw1DJw=}
